# Generated by Django 3.1.1 on 2020-10-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='CreateAccount',
        ),
    ]
