# Generated by Django 3.1.1 on 2020-10-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201016_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addunit',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
