# Generated by Django 3.1.1 on 2020-10-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201016_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='addunit',
            name='dealer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addunit',
            name='pricerange',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addunit',
            name='ram',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
