# Generated by Django 3.1.1 on 2020-10-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201018_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricerange',
            field=models.CharField(max_length=50),
        ),
    ]
