# Generated by Django 3.1.1 on 2020-10-30 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dealer'),
        ),
    ]
