# Generated by Django 3.1.1 on 2020-10-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20201030_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dealer',
            field=models.CharField(max_length=50),
        ),
    ]
