# Generated by Django 3.1.1 on 2020-10-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20201030_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
